package dev.stalla.model;

import dev.stalla.model.itunes.ItunesCategory;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ItunesCategoryFactoryTest {

    @Test
    @DisplayName("should be able to access the correct iTunes category instances from the companion object")
    public void testItunesCategoryFactory() {
        assertEquals(ItunesCategory.from("Arts"), ItunesCategory.Arts);
        assertEquals(ItunesCategory.from("Books"), ItunesCategory.Books);
        assertEquals(ItunesCategory.from("Design"), ItunesCategory.Design);
        assertEquals(ItunesCategory.from("Fashion & Beauty"), ItunesCategory.FashionAndBeauty);
        assertEquals(ItunesCategory.from("Food"), ItunesCategory.Food);
        assertEquals(ItunesCategory.from("Performing Arts"), ItunesCategory.PerformingArts);
        assertEquals(ItunesCategory.from("Visual Arts"), ItunesCategory.VisualArts);
        assertEquals(ItunesCategory.from("Business"), ItunesCategory.Business);
        assertEquals(ItunesCategory.from("Careers"), ItunesCategory.Careers);
        assertEquals(ItunesCategory.from("Entrepreneurship"), ItunesCategory.Entrepreneurship);
        assertEquals(ItunesCategory.from("Investing"), ItunesCategory.Investing);
        assertEquals(ItunesCategory.from("Management"), ItunesCategory.Management);
        assertEquals(ItunesCategory.from("Marketing"), ItunesCategory.Marketing);
        assertEquals(ItunesCategory.from("Non-Profit"), ItunesCategory.NonProfit);
        assertEquals(ItunesCategory.from("Comedy"), ItunesCategory.Comedy);
        assertEquals(ItunesCategory.from("Comedy Interviews"), ItunesCategory.ComedyInterviews);
        assertEquals(ItunesCategory.from("Improv"), ItunesCategory.Improv);
        assertEquals(ItunesCategory.from("Stand-Up"), ItunesCategory.StandUp);
        assertEquals(ItunesCategory.from("Education"), ItunesCategory.Education);
        assertEquals(ItunesCategory.from("Courses"), ItunesCategory.Courses);
        assertEquals(ItunesCategory.from("How To"), ItunesCategory.HowTo);
        assertEquals(ItunesCategory.from("Language Learning"), ItunesCategory.LanguageLearning);
        assertEquals(ItunesCategory.from("Self-Improvement"), ItunesCategory.SelfImprovement);
        assertEquals(ItunesCategory.from("Fiction"), ItunesCategory.Fiction);
        assertEquals(ItunesCategory.from("Comedy Fiction"), ItunesCategory.ComedyFiction);
        assertEquals(ItunesCategory.from("Drama"), ItunesCategory.Drama);
        assertEquals(ItunesCategory.from("Science Fiction"), ItunesCategory.ScienceFiction);
        assertEquals(ItunesCategory.from("Government"), ItunesCategory.Government);
        assertEquals(ItunesCategory.from("History"), ItunesCategory.History);
        assertEquals(ItunesCategory.from("Health & Fitness"), ItunesCategory.HealthAndFitness);
        assertEquals(ItunesCategory.from("Alternative Health"), ItunesCategory.AlternativeHealth);
        assertEquals(ItunesCategory.from("Fitness"), ItunesCategory.Fitness);
        assertEquals(ItunesCategory.from("Medicine"), ItunesCategory.Medicine);
        assertEquals(ItunesCategory.from("Mental Health"), ItunesCategory.MentalHealth);
        assertEquals(ItunesCategory.from("Nutrition"), ItunesCategory.Nutrition);
        assertEquals(ItunesCategory.from("Sexuality"), ItunesCategory.Sexuality);
        assertEquals(ItunesCategory.from("Kids & Family"), ItunesCategory.KidsAndFamily);
        assertEquals(ItunesCategory.from("Education for Kids"), ItunesCategory.EducationForKids);
        assertEquals(ItunesCategory.from("Parenting"), ItunesCategory.Parenting);
        assertEquals(ItunesCategory.from("Pets & Animals"), ItunesCategory.PetsAndAnimals);
        assertEquals(ItunesCategory.from("Stories for Kids"), ItunesCategory.StoriesForKids);
        assertEquals(ItunesCategory.from("Leisure"), ItunesCategory.Leisure);
        assertEquals(ItunesCategory.from("Animation & Manga"), ItunesCategory.AnimationAndManga);
        assertEquals(ItunesCategory.from("Automotive"), ItunesCategory.Automotive);
        assertEquals(ItunesCategory.from("Aviation"), ItunesCategory.Aviation);
        assertEquals(ItunesCategory.from("Crafts"), ItunesCategory.Crafts);
        assertEquals(ItunesCategory.from("Games"), ItunesCategory.Games);
        assertEquals(ItunesCategory.from("Hobbies"), ItunesCategory.Hobbies);
        assertEquals(ItunesCategory.from("Home & Garden"), ItunesCategory.HomeAndGarden);
        assertEquals(ItunesCategory.from("Video Games"), ItunesCategory.VideoGames);
        assertEquals(ItunesCategory.from("Music"), ItunesCategory.Music);
        assertEquals(ItunesCategory.from("Music Commentary"), ItunesCategory.MusicCommentary);
        assertEquals(ItunesCategory.from("Music History"), ItunesCategory.MusicHistory);
        assertEquals(ItunesCategory.from("Music Interviews"), ItunesCategory.MusicInterviews);
        assertEquals(ItunesCategory.from("News"), ItunesCategory.News);
        assertEquals(ItunesCategory.from("Business News"), ItunesCategory.BusinessNews);
        assertEquals(ItunesCategory.from("Daily News"), ItunesCategory.DailyNews);
        assertEquals(ItunesCategory.from("Entertainment News"), ItunesCategory.EntertainmentNews);
        assertEquals(ItunesCategory.from("News Commentary"), ItunesCategory.NewsCommentary);
        assertEquals(ItunesCategory.from("Politics"), ItunesCategory.Politics);
        assertEquals(ItunesCategory.from("Sports News"), ItunesCategory.SportsNews);
        assertEquals(ItunesCategory.from("Tech News"), ItunesCategory.TechNews);
        assertEquals(ItunesCategory.from("Religion & Spirituality"), ItunesCategory.ReligionAndSpirituality);
        assertEquals(ItunesCategory.from("Buddhism"), ItunesCategory.Buddhism);
        assertEquals(ItunesCategory.from("Christianity"), ItunesCategory.Christianity);
        assertEquals(ItunesCategory.from("Hinduism"), ItunesCategory.Hinduism);
        assertEquals(ItunesCategory.from("Islam"), ItunesCategory.Islam);
        assertEquals(ItunesCategory.from("Judaism"), ItunesCategory.Judaism);
        assertEquals(ItunesCategory.from("Religion"), ItunesCategory.Religion);
        assertEquals(ItunesCategory.from("Spirituality"), ItunesCategory.Spirituality);
        assertEquals(ItunesCategory.from("Science"), ItunesCategory.Science);
        assertEquals(ItunesCategory.from("Astronomy"), ItunesCategory.Astronomy);
        assertEquals(ItunesCategory.from("Chemistry"), ItunesCategory.Chemistry);
        assertEquals(ItunesCategory.from("Earth Sciences"), ItunesCategory.EarthSciences);
        assertEquals(ItunesCategory.from("Life Sciences"), ItunesCategory.LifeSciences);
        assertEquals(ItunesCategory.from("Mathematics"), ItunesCategory.Mathematics);
        assertEquals(ItunesCategory.from("Natural Sciences"), ItunesCategory.NaturalSciences);
        assertEquals(ItunesCategory.from("Nature"), ItunesCategory.Nature);
        assertEquals(ItunesCategory.from("Physics"), ItunesCategory.Physics);
        assertEquals(ItunesCategory.from("Social Sciences"), ItunesCategory.SocialSciences);
        assertEquals(ItunesCategory.from("Society & Culture"), ItunesCategory.SocietyAndCulture);
        assertEquals(ItunesCategory.from("Documentary"), ItunesCategory.Documentary);
        assertEquals(ItunesCategory.from("Personal Journals"), ItunesCategory.PersonalJournals);
        assertEquals(ItunesCategory.from("Philosophy"), ItunesCategory.Philosophy);
        assertEquals(ItunesCategory.from("Places & Travel"), ItunesCategory.PlacesAndTravel);
        assertEquals(ItunesCategory.from("Relationships"), ItunesCategory.Relationships);
        assertEquals(ItunesCategory.from("Sports"), ItunesCategory.Sports);
        assertEquals(ItunesCategory.from("Baseball"), ItunesCategory.Baseball);
        assertEquals(ItunesCategory.from("Basketball"), ItunesCategory.Basketball);
        assertEquals(ItunesCategory.from("Cricket"), ItunesCategory.Cricket);
        assertEquals(ItunesCategory.from("Fantasy Sports"), ItunesCategory.FantasySports);
        assertEquals(ItunesCategory.from("Football"), ItunesCategory.Football);
        assertEquals(ItunesCategory.from("Golf"), ItunesCategory.Golf);
        assertEquals(ItunesCategory.from("Hockey"), ItunesCategory.Hockey);
        assertEquals(ItunesCategory.from("Rugby"), ItunesCategory.Rugby);
        assertEquals(ItunesCategory.from("Running"), ItunesCategory.Running);
        assertEquals(ItunesCategory.from("Soccer"), ItunesCategory.Soccer);
        assertEquals(ItunesCategory.from("Swimming"), ItunesCategory.Swimming);
        assertEquals(ItunesCategory.from("Tennis"), ItunesCategory.Tennis);
        assertEquals(ItunesCategory.from("Volleyball"), ItunesCategory.Volleyball);
        assertEquals(ItunesCategory.from("Wilderness"), ItunesCategory.Wilderness);
        assertEquals(ItunesCategory.from("Wrestling"), ItunesCategory.Wrestling);
        assertEquals(ItunesCategory.from("Technology"), ItunesCategory.Technology);
        assertEquals(ItunesCategory.from("True Crime"), ItunesCategory.TrueCrime);
        assertEquals(ItunesCategory.from("TV & Film"), ItunesCategory.TvAndFilm);
        assertEquals(ItunesCategory.from("After Shows"), ItunesCategory.AfterShows);
        assertEquals(ItunesCategory.from("Film History"), ItunesCategory.FilmHistory);
        assertEquals(ItunesCategory.from("Film Interviews"), ItunesCategory.FilmInterviews);
        assertEquals(ItunesCategory.from("Film Reviews"), ItunesCategory.FilmReviews);
        assertEquals(ItunesCategory.from("TV Reviews"), ItunesCategory.TvReviews);
    }

}
