package dev.stalla.model.itunes

/*
public object Arts : ItunesCategory.Simple("Arts")
public object Books : ItunesCategory.Nested("Books", dev.stalla.model.itunes.Arts)
public object Design : ItunesCategory.Nested("Design", Arts)
public object FashionAndBeauty : ItunesCategory.Nested("Fashion & Beauty", Arts)
public object Food : ItunesCategory.Nested("Food", Arts)
public object PerformingArts : ItunesCategory.Nested("Performing Arts", Arts)
public object VisualArts : ItunesCategory.Nested("Visual Arts", Arts)

public object Business : ItunesCategory.Simple("Business")
public object Careers : ItunesCategory.Nested("Careers", Business)
public object Entrepreneurship : ItunesCategory.Nested("Entrepreneurship", Business)
public object Investing : ItunesCategory.Nested("Investing", Business)
public object Management : ItunesCategory.Nested("Management", Business)
public object Marketing : ItunesCategory.Nested("Marketing", Business)
public object NonProfit : ItunesCategory.Nested("Non-Profit", Business)

public object Comedy : ItunesCategory.Simple("Comedy")
public object ComedyInterviews : ItunesCategory.Nested("Comedy Interviews", Comedy)
public object Improv : ItunesCategory.Nested("Improv", Comedy)
public object StandUp : ItunesCategory.Nested("Stand-Up", Comedy)

public object Education : ItunesCategory.Simple("Education")
public object Courses : ItunesCategory.Nested("Courses", Education)
public object HowTo : ItunesCategory.Nested("How To", Education)
public object LanguageLearning : ItunesCategory.Nested("Language Learning", Education)
public object SelfImprovement : ItunesCategory.Nested("Self-Improvement", Education)

public object Fiction : ItunesCategory.Simple("Fiction")
public object ComedyFiction : ItunesCategory.Nested("Comedy Fiction", Fiction)
public object Drama : ItunesCategory.Nested("Drama", Fiction)
public object ScienceFiction : ItunesCategory.Nested("Science Fiction", Fiction)

public object Government : ItunesCategory.Simple("Government")

public object History : ItunesCategory.Simple("History")

public object HealthAndFitness : ItunesCategory.Simple("Health & Fitness")
public object AlternativeHealth : ItunesCategory.Nested("Alternative Health", HealthAndFitness)
public object Fitness : ItunesCategory.Nested("Fitness", HealthAndFitness)
public object Medicine : ItunesCategory.Nested("Medicine", HealthAndFitness)
public object MentalHealth : ItunesCategory.Nested("Mental Health", HealthAndFitness)
public object Nutrition : ItunesCategory.Nested("Nutrition", HealthAndFitness)
public object Sexuality : ItunesCategory.Nested("Sexuality", HealthAndFitness)

public object KidsAndFamily : ItunesCategory.Simple("Kids & Family")
public object EducationForKids : ItunesCategory.Nested("Education for Kids", KidsAndFamily)
public object Parenting : ItunesCategory.Nested("Parenting", KidsAndFamily)
public object PetsAndAnimals : ItunesCategory.Nested("Pets & Animals", KidsAndFamily)
public object StoriesForKids : ItunesCategory.Nested("Stories for Kids", KidsAndFamily)

public object Leisure : ItunesCategory.Simple("Leisure")
public object AnimationAndManga : ItunesCategory.Nested("Animation & Manga", Leisure)
public object Automotive : ItunesCategory.Nested("Automotive", Leisure)
public object Aviation : ItunesCategory.Nested("Aviation", Leisure)
public object Crafts : ItunesCategory.Nested("Crafts", Leisure)
public object Games : ItunesCategory.Nested("Games", Leisure)
public object Hobbies : ItunesCategory.Nested("Hobbies", Leisure)
public object HomeAndGarden : ItunesCategory.Nested("Home & Garden", Leisure)
public object VideoGames : ItunesCategory.Nested("Video Games", Leisure)

public object Music : ItunesCategory.Simple("Music")
public object MusicCommentary : ItunesCategory.Nested("Music Commentary", Music)
public object MusicHistory : ItunesCategory.Nested("Music History", Music)
public object MusicInterviews : ItunesCategory.Nested("Music Interviews", Music)

public object News : ItunesCategory.Simple("News")
public object BusinessNews : ItunesCategory.Nested("Business News", News)
public object DailyNews : ItunesCategory.Nested("Daily News", News)
public object EntertainmentNews : ItunesCategory.Nested("Entertainment News", News)
public object NewsCommentary : ItunesCategory.Nested("News Commentary", News)
public object Politics : ItunesCategory.Nested("Politics", News)
public object SportsNews : ItunesCategory.Nested("Sports News", News)
public object TechNews : ItunesCategory.Nested("Tech News", News)

public object ReligionAndSpirituality : ItunesCategory.Simple("Religion & Spirituality")
public object Buddhism : ItunesCategory.Nested("Buddhism", ReligionAndSpirituality)
public object Christianity : ItunesCategory.Nested("Christianity", ReligionAndSpirituality)
public object Hinduism : ItunesCategory.Nested("Hinduism", ReligionAndSpirituality)
public object Islam : ItunesCategory.Nested("Islam", ReligionAndSpirituality)
public object Judaism : ItunesCategory.Nested("Judaism", ReligionAndSpirituality)
public object Religion : ItunesCategory.Nested("Religion", ReligionAndSpirituality)
public object Spirituality : ItunesCategory.Nested("Spirituality", ReligionAndSpirituality)

public object Science : ItunesCategory.Simple("Science")
public object Astronomy : ItunesCategory.Nested("Astronomy", Science)
public object Chemistry : ItunesCategory.Nested("Chemistry", Science)
public object EarthSciences : ItunesCategory.Nested("Earth Sciences", Science)
public object LifeSciences : ItunesCategory.Nested("Life Sciences", Science)
public object Mathematics : ItunesCategory.Nested("Mathematics", Science)
public object NaturalSciences : ItunesCategory.Nested("Natural Sciences", Science)
public object Nature : ItunesCategory.Nested("Nature", Science)
public object Physics : ItunesCategory.Nested("Physics", Science)
public object SocialSciences : ItunesCategory.Nested("Social Sciences", Science)

public object SocietyAndCulture : ItunesCategory.Simple("Society & Culture")
public object Documentary : ItunesCategory.Nested("Documentary", SocietyAndCulture)
public object PersonalJournals : ItunesCategory.Nested("Personal Journals", SocietyAndCulture)
public object Philosophy : ItunesCategory.Nested("Philosophy", SocietyAndCulture)
public object PlacesAndTravel : ItunesCategory.Nested("Places & Travel", SocietyAndCulture)
public object Relationships : ItunesCategory.Nested("Relationships", SocietyAndCulture)

public object Sports : ItunesCategory.Simple("Sports")
public object Baseball : ItunesCategory.Nested("Baseball", Sports)
public object Basketball : ItunesCategory.Nested("Basketball", Sports)
public object Cricket : ItunesCategory.Nested("Cricket", Sports)
public object FantasySports : ItunesCategory.Nested("Fantasy Sports", Sports)
public object Football : ItunesCategory.Nested("Football", Sports)
public object Golf : ItunesCategory.Nested("Golf", Sports)
public object Hockey : ItunesCategory.Nested("Hockey", Sports)
public object Rugby : ItunesCategory.Nested("Rugby", Sports)
public object Running : ItunesCategory.Nested("Running", Sports)
public object Soccer : ItunesCategory.Nested("Soccer", Sports)
public object Swimming : ItunesCategory.Nested("Swimming", Sports)
public object Tennis : ItunesCategory.Nested("Tennis", Sports)
public object Volleyball : ItunesCategory.Nested("Volleyball", Sports)
public object Wilderness : ItunesCategory.Nested("Wilderness", Sports)
public object Wrestling : ItunesCategory.Nested("", Sports)

public object Technology : ItunesCategory.Simple("Technology")

public object TrueCrime : ItunesCategory.Simple("True Crime")

public object TvAndFilm : ItunesCategory.Simple("TV & Film")
public object AfterShows : ItunesCategory.Nested("After Shows", TvAndFilm)
public object FilmHistory : ItunesCategory.Nested("Film History", TvAndFilm)
public object FilmInterviews : ItunesCategory.Nested("Film Interviews", TvAndFilm)
public object FilmReviews : ItunesCategory.Nested("Film Reviews", TvAndFilm)
public object TvReviews : ItunesCategory.Nested("TV Reviews", TvAndFilm)
*/
